name: CI PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: source

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Code Build
      run: cd source && mvn -B package --file pom.xml

    - name: Image Build 
      run: |
        cd source
        docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-pipeline:$GITHUB_RUN_NUMBER-SNAPSHOT .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }}/hello-pipeline:$GITHUB_RUN_NUMBER-SNAPSHOT
