name: CI PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: source

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Code Build
      run: cd source && mvn -B package --file pom.xml

    - name: Image Build 
      run: |
        docker build -f ops/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/hello-pipeline:${{ env.GITHUB_RUN_NUMBER }}-SNAPSHOT .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }}/hello-pipeline:${{ env.GITHUB_RUN_NUMBER }}-SNAPSHOT
